import globals from "globals"
import pluginJs from "@eslint/js"
import tseslint from "typescript-eslint"
import pluginReact from "eslint-plugin-react"

export default [
  { files: ["**/*.{js,mjs,cjs,ts,jsx,tsx}"] },
  { languageOptions: { globals: globals.node } },
  pluginJs.configs.recommended,
  ...tseslint.configs.recommended,
  pluginReact.configs.flat.recommended,
  {
    rules: {
      "no-console": "warn",
      "no-debugger": "warn",
      "no-unused-vars": "warn",
      "no-undef": "warn",
      "no-var": "warn",
      "prefer-const": "warn",
      "prefer-arrow-callback": "warn",
      "prefer-template": "warn",
      "prefer-destructuring": "warn",
      "object-shorthand": "warn",
      "func-style": "warn",
      "spaced-comment": "warn",
      "arrow-spacing": "warn",
      "keyword-spacing": "warn",
      "comma-spacing": "warn",
      "comma-style": "warn",
      "space-before-blocks": "warn",
      "space-infix-ops": "warn",
      "eol-last": "warn",
      "brace-style": "warn",
      "array-bracket-spacing": "warn",
      semi: "off",
      quotes: ["warn", "double"],
      indent: ["warn", 2],
      "react/jsx-indent": ["warn", 2],
      "react/jsx-indent-props": ["warn", 2],
      "react/jsx-closing-bracket-location": "warn",
      "react/jsx-tag-spacing": "warn",
      "react/jsx-curly-spacing": "warn",
      "react/jsx-equals-spacing": "warn",
      "react/jsx-first-prop-new-line": "warn",
      "react/jsx-max-props-per-line": "warn",
      "react/jsx-wrap-multilines": "warn",
      "react/no-unused-prop-types": "warn",
      "react/prop-types": "warn",
      "react/self-closing-comp": "warn",
      "react/sort-comp": "warn",
      "react/jsx-no-bind": "warn",
      "react/jsx-no-target-blank": "warn",
      "react/no-unescaped-entities": "warn",
      "react/no-unknown-property": "warn",
      "react/react-in-jsx-scope": "warn",
      "react/display-name": "warn",
      "react/forbid-prop-types": "warn",
      "react/require-default-props": "warn",
      "react/default-props-match-prop-types": "warn",
      "react/no-children-prop": "warn",
      "react/no-redundant-should-component-update": "warn",
      "react/no-typos": "warn",
      "react/no-string-refs": "warn",
      "react/no-this-in-sfc": "warn",
      "react/no-unsafe": "warn",
      "react/prefer-stateless-function": "warn",
      "react/sort-prop-types": "warn",
      "react/state-in-constructor": "warn",
      "react/static-property-placement": "warn",
      "jsx-quotes": ["warn", "prefer-double"],
    },
  },
]
